import { NextRequest, NextResponse } from 'next/server';
import { fetchRecords, updateRecord } from '@/lib/airtable';
import { AIRTABLE } from '@/lib/constants';
import { Draft } from '@/lib/types';

const TABLE = AIRTABLE.TABLES.DRAFTS;

function mapDraft(record: { id: string; fields: Record<string, unknown> }): Draft {
  const f = record.fields;
  return {
    id: record.id,
    draftTitle: (f['Draft Title'] as string) || '',
    type: (f['Type'] as Draft['type']) || 'Time-In',
    date: (f['Date'] as string) || '',
    versionLabel: (f['Version Label'] as Draft['versionLabel']) || 'Version A',
    body: (f['Body'] as string) || '',
    reasoning: (f['Reasoning'] as string) || '',
    draftStatus: (f['Draft Status'] as Draft['draftStatus']) || 'Generated',
    generatedAt: (f['Generated At'] as string) || '',
    generatedBy: (f['Generated By'] as Draft['generatedBy']) || 'n8n AI Agent',
  };
}

export async function GET(request: NextRequest) {
  try {
    const date = request.nextUrl.searchParams.get('date');
    const type = request.nextUrl.searchParams.get('type');

    if (!date) {
      return NextResponse.json({ error: 'date parameter required' }, { status: 400 });
    }

    let formula = `DATESTR({Date})='${date}'`;
    if (type) {
      formula = `AND(DATESTR({Date})='${date}', {Type}='${type}')`;
    }

    const records = await fetchRecords(TABLE, {
      filterByFormula: formula,
    });

    const drafts = records.map(mapDraft);
    return NextResponse.json(drafts);
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const body = await request.json();
    const { id, fields } = body as { id: string; fields: Record<string, unknown> };

    if (!id || !fields) {
      return NextResponse.json({ error: 'id and fields required' }, { status: 400 });
    }

    const record = await updateRecord(TABLE, id, fields);
    return NextResponse.json(mapDraft(record));
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
